[depscan.csaf.document]
category = "csaf_security_advisory"
title = ""


[depscan.csaf.publisher]
# Required
category = "vendor" # Valid categories are: coordinator, discoverer, other, translator, user, vendor
name = "Vendor McVendorson"
namespace = "https://appthreat.com"
# Optional
contact_details = "vendor@mcvendorson.com"
issuing_authority = ""


# A revision entry will be automatically added to this file if you have enabled auto revision history and the status is "final"
# The current date/time is default if not provided
# id is required and best set by the document issuing authority, but we will create one if not provided
[depscan.csaf.tracking]
# Required
current_release_date = ""   # Do not enclose dates if in valid datetime format
id = "Temp ID"
initial_release_date = ""
status = "draft"    # Valid statuses are: draft, final, interim
version = "1"
# Optional
#aliases = []


# TODO: Sort these by date descending before exporting
[depscan.csaf.revision_history]
rev_1 = {date=2022-09-22T20:54:06.186927,number="1",summary="Initial",filepath="path/to/rev1.json"}
rev_2 = {date=2023-09-22T20:54:06.186927,number="2",summary="Update",filepath=""}


[depscan.csaf.notes]
# Category and text are required to add a note, add as many notes as you need
# Valid categories are: description, details, faq, general, legal_disclaimer, other, summary
note1 = {audience="devs",category="general",text="la di da",title="note to devs"}


#[depscan.csaf.product_tree]
#full_product_names = ["myproduct1", "myproduct2"]


[depscan.csaf.distribution]
text = "Sample text"
# Label is required if tlp included
tlp = {label="AMBER", url="https://tlp.com"}


[depscan.csaf.references]
# Summary and url are required, include as many ref as you like
# Category can be either "external" or "self"
ref1 = {category="self",summary="summary1",url="https://url.com"}
ref2 = {category="external",summary="summary2",url="https://url.com"}


[depscan.csaf.auto]
increment_revisions = true
product_tree = true
release_dates = true







